### ISSUE TITLE
Design Decision for AIsettingsV3.hpp ?

### ISSUE THREAD

**Issue by xetra11** [genesis92x/VcomAI-3.0#68]
Hey guys,

I just refactored my own project to have only 3DEN editor modules to be used as configuration/setup. I also thought about having an external file like Vcom here to lay down as configuration but could not chose it to be the final way to go.

Can you explain why exactly take this approach over mission/editor based configuration? Is it because therefore you can change configurations without having to repack and export a mission using Vcom?

greets
Charlie

**Comment by Aarnoman** [comment]
I'm not sure what your question is. If you are asking why the GitHub vcom repository is set out to be placed in a mission instead of pbo add-on, it is to expedite the process of testing code as there is no need to rebuild the pbo and relaunch the game whenever changes are made. Once we are happy with the state of it we repackage it as a pbo addon for public use.

**Comment by xetra11** [comment]
Nah I meant to ask why you using **AIsettingsV3.hpp** as user configuration instead i.e. CBA Settings or BIS editor modules? I was about to do the same thing but people told me to rely on the mentioned two approaches instead of external configuration files. Just want to ask about your decision arguments here to reevaluate it for my own project.

**Comment by Aarnoman** [comment]
It's mostly cba options at this point, the configuration file is their to do any other settings in the meantime that haven't been entered into the cba settings file.

**Comment by xetra11** [comment]
Ok I see. Thanks.
