### ISSUE TITLE
AI placed-mines can't be disabled, when playing with ACE3

### ISSUE THREAD

**Issue by madpat3** [genesis92x/VcomAI-3.0#78]
When playing with ACE and VCM_MINECHANCE is set to e.g. 100%, there is no way to disable those mines.
They always explode, when trying to do so.

**Comment by Freddo3000** [comment]
That is because the mines aren't regular mines. they are the "scripted" variants of the mines.

These do not blow up by themselves, but has a script attached to them that makes them blow up whenever an enemy is near them. This was done in order to make the AI able to detect the mines and also not blow themselves up when they place them.

If there isn't any way to disable the mines then it is up to ACE to support the scripted versions of mines.
