### ISSUE TITLE
AI groups in SAFE mode do not auto engage enemies after 3.2.1 release

### ISSUE THREAD

**Issue by GoldJohnKing** [genesis92x/VcomAI-3.0#96]
**Describe the bug**

I've noticed that after 3.2.1 release, some mission-spawned AI units in "SAFE" mode do not auto engage enemies after spotting them. Those AI has an abnormal low willings to spot or engage players, even though their group members are being attacked or killed by players. This happens especially on AI vehicles or small AI infantry groups. AI vehicles would just drive pass standing player infantries or vehicles, chasing their waypoints far away in another city, while AI infantry groups do not change into "AWARE" mode even their group members are just killed before them.

According to this wiki(https://community.bistudio.com/wiki/AI_Behaviour), AI should auto change into AWARE mode if they spot enemy units.

However, according to my test, with VCOM 3.2.1 or 3.2.2 on, most (or all?) of the AI in SAFE mode do not change into AWARE mode when they spot enemies. Many players also report that killing one of the infantry in a "SAFE" group wont cause the rest ones change to "AWARE" mode. And when players are engaging one group with a "SAFE" group nearby just beside the attacked group, the "SAFE" group just stand there and watch the fight. AI seems only engage player when they can both spot and are attacked by players. This seems also happens on Zeus spawned units, but I still do not have enough test on it.

I used to first report this issue on https://github.com/genesis92x/VcomAI-3.0/issues/80 assuming this as an "reinforcement range" issue and I'm not sure about it. Now I have certain proofs and many specific player report. I'm not sure if I reach the point, so if there's some misunderstandings, please let me know.

**To Reproduce**

See how a "SAFE" AI vehicle units behave:
1. Find a enemy vehicle in "SAFE" mode or has "SAFE" waypoints.
2. Chase them by a car, or just teleport to the front of them.
3. AI just drive pass the player, chasing their waypoints far away in another city, and seems to have no willings to engage players.

See how a "SAFE" AI infantry group behave:
1. Find a enemy group in "SAFE" mode or has "SAFE" waypoints, with another "AWARE" group nearby is better.
2. Kill one of their member without being spotted.
3. You can see the "AWARE" group starts engage mode, while the "SAFE" group do nothing but wathing their member killed.

**Expected behavior**
AI groups or units should auto engage enemies upon soptting them, or change into "AWARE" mode once being attacked or being threatened, instead of doing nothing.

**Screenshots**
Temporarily, none.

**VCOM Version:**
 - Branch: [Master]
 - Version [3.2.1] or [3.2.2]
 
**Additional mods used:**
 - CBA_A3 (v3.10.1.190316)
 - ACE3 (Newest Steam Workshop release)

**Additional context**
I use FIA East as enemy faction, and tested both in day and night, frequently (or always) happen.

**Comment by genesis92x** [comment]
Thank you for the report. We will be tweaking this behavior from SAFE. I went ahead and made it so squads go straight into COMBAT mode when they lose a member of their squad. And AI in SAFE mode definitely have drastically reduced detection skills by default.

Hopefully with the increase of the revealing from gunfire, they will become more active again.

Again, thank you for the detailed report. I just went on a little rant about the steam forums. I wish I could disable the comment section there.

There should be a release again by Sunday **(Freddo, if you are reading this)**

This will allow us to iron out all these little bugs :) It helps to have people like you who are willing to test.

**Comment by GoldJohnKing** [comment]
Yep, I get your point.
By the way, users on Steam are just normal users, they are not even server admins, not even "a little bit" developers. It's frustrating and useless to have your attention on steam fourms. I suggest just ignoring them, and move more attention on Github. Those feedback by who wont use github should be ignored as a basic filter.
No matter how, thanks for your efforts on this project.

**Comment by GoldJohnKing** [comment]
Update:
I've noticed that some of those SAFE AI do auto change their mode into AWARE or COMBAT, but they still "freeze" and have no response to attack or anything. I manually change their mode to safe or aware then change it back to COMBAT again, they start to "unfreeze" and response to attack.

**Comment by Freddo3000** [comment]
BIs Autocombat was disabled in favour of our own implementation, however it wasn't completely done by the time that the update was pushed.

**Comment by genesis92x** [comment]
I am very curious how you do this implementation @Freddo3000 If you can make a system that works well, for a majority of situations, I will definitely be impressed. Last year I attempted to create a new implementation of the default COMBAT behaviors, and it failed terribly. 

The performance was okay, but the AI were not reacting properly across dynamic situations. Ultimately, it  either resulted in players not being able to see a difference at all, or worse, they thought my new fancy implementation made the AI stupid.

Which made me sad, because my fancy system was so much more complex.

Come to find out that it was better to not mess with the behaviors at all...

The **new** FFE artillery system is a great example. I love the system personally, but that's because I see how it works underneath. The group I typically play with does not see a drastic difference between the old Vcom artillery and the new fancy FFE system. **They just see rounds landing around them** 

So at the end of the day, I would love to see if you can implement a system which actually creates a difference in experience for the players. FPS Cost vs Fun factor!

If you would like help with this, please let me know how I can help!

Can't wait to see what you can come up with :)
